### ISSUE TITLE
Should not be refetching the remote Git repository

### ISSUE THREAD

**Issue by khell** [Microsoft/azure-app-service-plugin#23]
When deploying an Azure webapp via Git, the .azure-deploy repository is recreated every single time i.e. git init, then git fetch is run. This may have been the simple way out, but it is problematic when a) the number of remote objects is really big and b) it takes so long to fetch it times out (after 10 minutes).

Can this please be changed? Our non-plugin manual way is to just do a diff of changed files.

**Comment by ArchangelSDY** [comment]
Do you clean your workspace each time before build? Git fetch is incremental so if you do not remove the .azure-deploy repository it will only download the newly added objects.

Besides, could you provide more details about why your objects are big? Binaries such as images should usually be distributed separately by CDN and should not be deployed along with code files.

**Comment by panmanphil** [comment]
I am getting timeouts as well. The binaries are .net dlls so a cdn would not help. It really isn't clear to me that the fetch is the problem though because I am getting this timeout before the first deploy ever happens, so there is nothing to download from the azure site. I had assumed the timeout is the upload. 

Is there a place to set a longer timeout?

**Comment by ArchangelSDY** [comment]
@panmanphil So if you execute command `C:\Program Files\Git\bin\git.exe fetch --tags --progress https://xxxxxxxxscm.azurewebsites.net:443/xxxxxxxxx.git +refs/heads/*:refs/remotes/origin/*` manually, it will succeed but will take more than 10 minutes?

**Comment by panmanphil** [comment]
That command, from the command line, on the Jenkins master succeeded in less than 10 seconds

**Comment by ArchangelSDY** [comment]
Does your job run on master too? If it runs on a slave, have you tried to execute the command on slave?

**Comment by panmanphil** [comment]
Unfortunately, the slaves aren't currently running so all jobs run on master.

**Comment by ArchangelSDY** [comment]
Looks like you are running on Windows. Could you try to reinstall your git and **make sure not to enable Git Credential Manager** during installation? It is known to pop up a dialog for credentials which will block jenkins job.

**Comment by khell** [comment]
Just wanted to update that I increased the timeout value of Git on my end, so _my_ issue is resolved.

**Comment by panmanphil** [comment]
@ArchangelSDY I have confirmed that disabling the git credential manager for windows solved this problem. I was able to do this without reinstalling with `git config --edit --system` and removing the line that says `helper = manager`. So this issue is resolved for me as well. The fact that binary nuget packages, lots of packages were added to the git repo may make git a less than ideal way of deploying a .net app to azure, but that is a separate issue.

**Comment by ArchangelSDY** [comment]
According to [this article](https://github.com/projectkudu/kudu/wiki/Deployment) if you are deploying an ASP.NET Web Application Project, you can just check in source code and msbuild will run after 'git push' and will build the project for you. You can check if that meets your requirements.

**Comment by panmanphil** [comment]
There are probably simple enough sites where that makes sense, but throw in bundling, minification, typescript, and all the other stuff modern web apps have, I think a tested build artifact from a jenkins makes more sense. Thanks for your help
